name: Expressions and Contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expression and Contexts triggered by ${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
  runs-on-issues-and-PRs:
    runs-on: ubuntu-latest
    if: contains(fromJson('[issues, pull_request]'), github.event_name)
    steps:
      - name: Run only if issue has a bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: echo ${{ join(github.event.issue.labels.*.name, ',') }}

  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 3 }}
          echo ${{ true && false }}
          echo ${{ true || (1 > 3)}}
          echo ${{ 'string' == 'STRING'}}
      - name: Dump contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
